const mainColor = {
  white: 'white',
  black: 'black',
  blue: '#2D9CDB',
  blue3: '#56CCF2',
  blue2: '#1BA0E2',
  yello: '#FAD70F',
  alto: '#DCDCDC',
  silver: '#BDBDBD',
  concrete: '#F2F2F2',
  red: '#D7463C',
  gray: '#333333',
  abu: '#E0E0E0',
  abuTua: '#707070',
  abuMuda: '#C2C2C2',
  green: '#07E024',
  merah: '#D7463C',
  grayMuda: '#828282',
  purple: '#5856D7',
};

export const colors = {
  text: {
    white: mainColor.white,
    black: mainColor.black,
    placeholder: mainColor.alto,
    blue: mainColor.blue,
    blue2: mainColor.blue2,
    gray: mainColor.gray,
    error: mainColor.red,
    abu: mainColor.abu,
    abuTua: mainColor.abuTua,
    green: mainColor.green,
    grayMuda: mainColor.grayMuda,
    yello: mainColor.yello,
    silver: mainColor.silver,
    purple: mainColor.purple,
    blue3: mainColor.blue3,
    concrete: mainColor.concrete,
  },
  bg: {
    white: mainColor.white,
    black: mainColor.black,
    blue: mainColor.blue,
    yello: mainColor.yello,
    gray: mainColor.gray,
    abu: mainColor.abu,
    abuTua: mainColor.abuTua,
    concrete: mainColor.concrete,
    red: mainColor.red,
    grayMuda: mainColor.grayMuda,
    abuMuda: mainColor.abuMuda,
    silver: mainColor.silver,
    green: mainColor.green,
    purple: mainColor.purple,
    blue3: mainColor.blue3,
    blue2: mainColor.blue2,
  },
};
